### ISSUE TITLE
Improve fig 4

### ISSUE THREAD

**Issue by trangdata** [HallLab/paper_2020_tpot_actg#1]
We (@jrm5100 and I) discussed earlier today about how Figure 4 needs to be a little more succinct. I also think we should focus on "rank" rather than absolute importance score because relative importance is more relevant to our discussion.

Here are some ideas I have (preliminary):

### A heatmap:
This idea looked good in my head, but I think too many of these tiles are empty:
![image](https://user-images.githubusercontent.com/1679452/87381464-ccb37000-c562-11ea-80ee-3f04dde8ba8d.png)

### Standard importance plot but with multiple pipelines:
I jittered the points a little so we could see how many pipelines the bin is present in, but it's still a bit hard to see how many are actually there.
![image](https://user-images.githubusercontent.com/1679452/87381687-48adb800-c563-11ea-91c6-78f0222732a5.png)

I'm leaning toward using the second plot, given that the main text focuses on the relevance of these bins rather than how many pipelines contain it. We can adjust how many bins we want for each phenotype. Let me know what you guys think!

**Comment by jrm5100** [comment]
Of these I think the second one looks better, but I'm not quite wrapping my head around it.

What is the median rank?  Is there any significance to the horizontal lines connecting some dots, or is it just an artifact of how the plot works?

Another option could be to just reshape what we have, like 2 rows of 5 for each phenotype.

**Comment by trangdata** [comment]
> What is the median rank?

It's the median of the rank of each bin across 100 replicates for one pipeline (similar to the middle line in the boxplot but for ranks instead of absolute importance scores).

> Is there any significance to the horizontal lines connecting some dots, or is it just an artifact of how the plot works?

We can remove these, but I was trying to connect all the pipelines that the same bin belongs to. For example, we can see that DMTF1 was the 3rd most important bin in one pipeline and the 4th most important in a few others.

> Another option could be to just reshape what we have, like 2 rows of 5 for each phenotype.

You mean sticking with the boxplots? I think it's quite confusing for others to see that many of these are just 0. I also think the variation within the 100 replicates for each pipeline is not necessarily what we want to focus on. If the main text focuses on the important bins and how they affect the phenotype, I think we should design our figures to demonstrate that.

**Comment by trangdata** [comment]
Oooh another I just have is [UpSet plot](https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#upset-making-the-plot). This way, we can incorporate the pipeline performance score and feature importance score for each phenotype.

**Comment by trangdata** [comment]
I'm probably spending way too much time on this, but how about something like this (for biliruben):

![biliruben](https://user-images.githubusercontent.com/1679452/87584988-5cb10100-c6ac-11ea-93df-dbd5a0c8fef8.png)


Average importance score on the left shows the average of each gene's importance scores across the pipelines that contain the genes (on the right). We can also see that pipeline 4-10 pick the same features (and probably have the same pipeline structure and operators). I also think connecting the genes in the same pipeline with a line (aka pipe) makes sense.

**Comment by jrm5100** [comment]
I think I like the right half of the image.  I don't know that the left half adds all that much- basically just showing an average value of the colors on the right, correct?

I'll take a crack at my new idea tomorrow.  I'm not yet convinced that our ideas for figure 4 thus far are an improvement that is important enough to update the paper now.  I do like the new figure 2 though and the svg files for the pipeline diagrams.

**Comment by jrm5100** [comment]
Resolved by #2
